### ISSUE TITLE
Suggestion: use terraform templates provided by the official PAS release in Pivotal Network

### ISSUE THREAD

**Issue by olle-brkt** [pivotal-cf/pcf-pipelines#264] opened 2018-01-06 03:55 UTC
Now that PCF 2.0 has launched, the Cloud Formation templates you used to paving the IAAS with the infrastructure needed to deploy PCF has been replaced by terraform templates. (In AWS)

In my opinion, it would be great if pcf-pipelines would use these templates as well, so that the PCF deployment you deploy using these pipelines is as close to the "official" reference architecture as possible. For customers, this would mean that moving from deploying PCF manually to using concourse automation is more natural since that template used is the same.

Is this something that you have been investigating, or maybe already have planned?

Thanks

**Comment by abbyachau** [comment] 2018-01-10 00:17
Hi @olle-brkt, please could you clarify your question. We've always used terraform to pave PCF for AWS, and we've used the ref arch for the templates to deploy subnets, azs, etc. Let me know if I've misconstrued your original feedback, thanks.

**Comment by olle-brkt** [comment] 2018-01-12 01:26
Hi @abbyachau!

Yes, I know that you use terraform to pave PCF - but the docs for PCF regarding installing PCF used to use Cloud Formation for AWS. 

The Cloud Formation template was also found in the PivNet release for ERT, where as the new terraform template is found in the PivNet release for PAS.
Compare:
https://docs.pivotal.io/pivotalcf/1-12/customizing/cloudform-install.html
https://docs.pivotal.io/pivotalcf/2-0/customizing/aws-terraform.html 

---

I'm simply wondering if it might be a good idea to use the terraform template in the PivNet release for PAS as a base when designing the `pcf-pipelines` terraform template  - meaning the transition from using the terraform template in PAS to using these pipelines would be even easier.

Hope that cleared up any confusion! :)

**Comment by abbyachau** [comment] 2018-01-17 22:26
Hi @olle-brkt, thanks for the feedback.The pipelines are based on the [reference architecture](https://docs.pivotal.io/pivotalcf/1-11/refarch/aws/aws_ref_arch.html) by design, and not the Cloudformation template. We would like to consolidate the terraforming and naming conventions efforts across orgs but as this product is not GA yet, we have other priorities at the moment. 

Are you working with a specific customer at the moment? I forget what your use case is, but you should refer to the reference architecture for more information. Let me know if you have any questions.

**Comment by abbyachau** [comment] 2018-01-25 22:15
Hi @olle-brkt, closing this issue, please reach out again if you have any further comments. Thanks.

**Closed by abbyachau** 2018-01-25 22:15 UTC
Labels: unscheduled
