### ISSUE TITLE
Configuring ERT PCF 1.10

### ISSUE THREAD

**Issue by Murryy79** [pivotal-cf/pcf-pipelines#121] opened 2017-06-14 20:58 UTC
**While we are trying to set this property .properties.uaa.customize_username_label using the following api command,** 

_$CMD -t https://$OPS_MGR_HOST -u $OPS_MGR_USR -p $OPS_MGR_PWD -k configure-product -n cf -p "$CF_AUTH_PROPERTIES"_

**With these values for the specified properties**

root@b1e3dd53-e9e3-429f-7ff1-bb1e86c275ac:/tmp/build/a804cf7b# echo $CF_AUTH_PROPERTIES
{ ".properties.uaa": { "value": "ldap" }, ".properties.uaa.ldap.url": { "value": "ldaps://vds.discoverfinancial.com:636" }, ".properties.uaa.ldap.credentials": { "value": { "identity": "uid=cldfundry,ou=Apps,ou=Admin,o=DFSI", "password": "<redacted>" } }, ".properties.uaa.ldap.search_base": { "value": "o=DFSI" }, ".properties.uaa.ldap.search_filter": { "value": "uid={0}" }, ".properties.uaa.ldap.group_search_base": { "value": "" }, ".properties.uaa.ldap.group_search_filter": { "value": "member={0}" }, ".properties.uaa.ldap.mail_attribute_name": { "value": "mail" }, ".properties.uaa.ldap.first_name_attribute": { "value": "true" }, ".properties.uaa.ldap.last_name_attribute": { "value": "true" }, ".properties.uaa.customize_username_label": { "type": "string" "value": "RACF" } }
root@b1e3dd53-e9e3-429f-7ff1-bb1e86c275ac:/tmp/build/a804cf7b# 

**We are receiving this error.**

root@b1e3dd53-e9e3-429f-7ff1-bb1e86c275ac:/tmp/build/a804cf7b# $CMD -t https://$OPS_MGR_HOST -u $OPS_MGR_USR -p $OPS_MGR_PWD -k configure-product -n cf -p "$CF_PROPERTIES" -pn "$CF_NETWORK" -pr "$CF_RESOURCES"
configuring product...
setting properties
could not execute "configure-product": failed to configure product: request failed: unexpected response:
HTTP/1.1 400 Bad Request
Content-Length: 0
Connection: keep-alive
Content-Type: text/html; charset=utf-8
Date: Wed, 14 Jun 2017 20:49:03 GMT
Server: nginx/1.4.6 (Ubuntu)
Strict-Transport-Security: max-age=31536000
X-Request-Id: 8461a388-eba9-429d-a545-2e2b43cdc9fa
X-Runtime: 0.001188

**What could be the cause of such a response from the API?**

**Comment by Murryy79** [comment] 2017-06-14 20:59
I should have mentioned that other api calls are working as desired when configuring the rest of the ERT Tile.

**Comment by krishicks** [comment] 2017-06-14 22:32
What pipeline, what version of pcf-pipelines?

**Comment by Murryy79** [comment] 2017-06-15 13:03
vSphere pcf install Pipeline for 1.10

**Comment by krishicks** [comment] 2017-06-15 14:38
What version of pcf-pipelines?

**Comment by Murryy79** [comment] 2017-06-15 15:49
PCF ERT 1.10.9 build18.
don't know pipeline version. where do i find that?

**Comment by krishicks** [comment] 2017-06-15 16:01
If you got it from git, it's the git SHA. If you got it from PivNet, it's the release version.

**Comment by Murryy79** [comment] 2017-06-15 17:51
got it from git

**Comment by krishicks** [comment] 2017-06-16 15:05
I can't help you without knowing what specific version of pcf-pipelines you were using.

Until you can provide the relevant details or a reproducible test case I'm going to close this issue.

**Closed by krishicks** 2017-06-16 15:05 UTC
Labels: unscheduled

**Comment by krishicks** [comment] 2017-08-05 04:21
This is broken because your JSON is invalid.

The line you have added:

```
".properties.uaa.customize_username_label": { "type": "string" "value": "RACF" } }
```

Is missing a comma between `"string" "value"`

**Comment by Murryy79** [comment] 2017-08-05 17:04
Thanks. I will try your suggestions Monday
