### ISSUE TITLE
AWS Ops Manager upgrades timed out during replace-opsman-vm task

### ISSUE THREAD

**Issue by xyloman** [pivotal-cf/pcf-pipelines#122] opened 2017-06-15 15:32 UTC
I have been fighting with this issue for a few weeks now and had not posted anything until we got our pipelines built out and maintained using pcf-pipelines-maestro.  We also have upgraded our AWS foundation to leverage pcf-pipelines 0.15.0 from pivnet.  When we get to the task replace-opsman-vm
 for job upgrade-opsmgr we continuously get the error ```2017/06/15 15:20:10 error: timed out waiting for instance to become TERMINATED (last status was stopped)```

**Comment by xchapter7x** [comment] 2017-06-23 17:03
this was an issue with a tool called cliaas, which is bundled in our base image.
this should just start working as the next time the task runs it will pull the latest docker image, which now contains the fix.

for reference: https://github.com/pivotal-cf/cliaas/releases/tag/v0.1.9

closing this for now, let me know if the issue is not resolved and we can re-open @xyloman

**Closed by xchapter7x** 2017-06-23 17:03 UTC
Labels: delivered

**Comment by sakkoub** [comment] 2018-09-06 03:44
@xyloman I am still facing this issue with PCF pipelines version v0.23.6, please any advise
