### ISSUE TITLE
Terraformed firewall rule allow-ert-all overly restrictive

### ISSUE THREAD

**Issue by krishicks** [pivotal-cf/pcf-pipelines#71] opened 2017-05-16 21:14 UTC
From @cholick, originally in gcp-concourse:

> GCP installation instructions don't restrict traffic flow to tags, see:
> http://docs.pivotal.io/pivotalcf/1-9/customizing/gcp-prepare-env.html#firewall_rules
> 
> But the terraformed firewall rule for internal traffic does:
> https://github.com/pivotal-cf/gcp-concourse/blob/master/terraform/firewalls.tf#L76-#L77
> 
> This creates traffic issues on bosh-deployed / odb vms, which don't get tagged in the same way.
> 
> cc @JaredGordon @miyer-pivotal

**Comment by JaredGordon** [comment] 2017-05-17 13:15
+1

**Comment by abbyachau** [comment] 2017-10-24 00:26
Hi @krishicks, it looks like this issue has moved on:

GCP docs 1.12 docs for firewall rules: 

http://docs.pivotal.io/pivotalcf/1-12/customizing/gcp-prepare-env.html#firewall_rules

and the terraform firewall rules we use for the pipelines:

https://github.com/pivotal-cf/pcf-pipelines/blob/master/install-pcf/gcp/terraform/firewalls.tf

I will close this issue unless you have additional feedback, thank you.

**Comment by krishicks** [comment] 2017-10-24 00:56
It isn’t my issue.

**Comment by abbyachau** [comment] 2017-10-24 19:21
Confirmed with Matt Cholick that we can close this story.

**Closed by abbyachau** 2017-10-24 19:21 UTC
Labels: scheduled
